### PR TITLE
[13.0][ADD] account_reporting_volume: New module to show the volume in the invoices analysis view

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT36336

please @victoralmau @sergio-teruel

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Shouldn't it be called `account_invoice_pivot_volume` (`account_invoice_report_volume` may be misleading)?

**Comment by CarlosRoca13** [comment]
IDK, I take as reference this other: https://github.com/OCA/account-invoice-reporting/tree/13.0/account_reporting_weight

**Comment by pedrobaeza** [comment]
I see. There's no good name, as core uses `report` for both pivot and QWeb. I suppose it was put `reporting` for differentiating this module from the existing one modifying the report. In other places, we have use the word `pivot` for such differentiation, but then it wouldn't be homogeneous with the existing, so OK to keep it.

**Review by sergio-teruel — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
