### PR TITLE
[14.0][MIG] account_invoice_line_report: Migration to 14.0

### PR DESCRIPTION
**Pull request by xavierjimenez**
Migration to 14.0 of the module account_invoice_line_report

### CODE REVIEW

**Comment by xavierjimenez** [comment]
Could you do a review if possible, please? @kittiu @joao-p-marques 

Thanks!

**Review by chusamo — APPROVED** [review]
Code review OK. LGTM it is added the move_id I think it's useful to see in the tree view nice:)

**Review by joao-p-marques — APPROVED** [review]

**Comment by joao-p-marques** [comment]
LGTM :+1: 
Code and functional review

**Review by anasuarez1 — APPROVED** [review]
Functional Review ok!

**Pull request merged**
