### PR TITLE
[14.0][IMP] account_invoice_report_grouped_by_picking: Show section and notes

### PR DESCRIPTION
**Pull request by manuelregidor**
From https://github.com/OCA/account-invoice-reporting/pull/258

T-5666

### CODE REVIEW

**Comment by manuelregidor** [comment]
@luis-ron @HaraldPanten @ValentinVinagre

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Comment by ValentinVinagre** [comment]
@Jesarregui @angelgarciadelachica  could u review please?

**Review by angelgarciadelachica — APPROVED** [review]

**Comment by angelgarciadelachica** [comment]
LGTM 👍🏻

**Review by Jesarregui — CHANGES_REQUESTED** [review]
Functional review:

1. In the order I add 3 sections and 3 notes (Shot 1). 
image

2. These sections and notes are correctly inherited on the invoice (Shot 2).
image

3. On the form, section 3 and note 3 are not shown, since there is no line with a product afterwards (Screenshot 3).

image


I do not validate this PR functionally.

**Comment by ValentinVinagre** [comment]
> Functional review:
> 
> 1. In the order I add 3 sections and 3 notes (Shot 1).
>    image
> 2. These sections and notes are correctly inherited on the invoice (Shot 2).
>    image
> 3. On the form, section 3 and note 3 are not shown, since there is no line with a product afterwards (Screenshot 3).
> 
> image
> 
> I do not validate this PR functionally.

@manuelregidor could u review please?

**Comment by manuelregidor** [comment]
@Jesarregui @ValentinVinagre This PR is based on https://github.com/OCA/account-invoice-reporting/pull/258 Please, note that the issue addressed by @Jesarregui happens in v13 too. Don't you think we should apply this IMP first and then think about the FIX?

**Comment by ValentinVinagre** [comment]
> @Jesarregui @ValentinVinagre This PR is based on #258 Please, note that the issue addressed by @Jesarregui happens in v13 too. Don't you think we should apply this IMP first and then think about the FIX?

I would make another fix commit on this imp in the same PR.

**Pull request closed without merging**
