### PR TITLE
[15.0][MIG] account_invoice_report_due_list: Migration to version 15.0

### PR DESCRIPTION
**Pull request by LudLaf**
@Tecnativa TT36938

### CODE REVIEW

**Comment by LudLaf** [comment]
@cesar-tecnativa please review.

**Comment by LudLaf** [comment]
@pedrobaeza please review.

**Review by pedrobaeza — APPROVED** [review]
Code and functional review

**Review by victoralmau — APPROVED** [review]
Code and functional review OK

**Pull request merged**
