### PR TITLE
[16.0][MIG] account_reporting_volume: Migration to version 16.0

### PR DESCRIPTION
**Pull request by stefan-tecnativa**
cc @Tecnativa TT44311

@CarlosRoca13 @pilarvargas-tecnativa please review!

### CODE REVIEW

**Review by CarlosRoca13 — APPROVED** [review]

**Review by pilarvargas-tecnativa — APPROVED** [review]
thanks :)

**Comment by stefan-tecnativa** [comment]
What about this one? @pedrobaeza

**Pull request merged**
