### PR TITLE
[MIG] account_invoice_comment_template: Migration to 12.0

### PR DESCRIPTION
**Pull request by rven**

### CODE REVIEW

**Comment by rven** [comment]
Depends on https://github.com/OCA/account-invoice-reporting/pull/96

**Comment by pedrobaeza** [comment]
Please rebase

**Comment by rven** [comment]
Re-base is done!

**Review by emagdalenaC2i — APPROVED** [review]

**Comment by emagdalenaC2i** [comment]
#96 is merged

**Pull request merged**
