### PR TITLE
[12.0][FIX] account_invoice_report_due_list: Report date format

### PR DESCRIPTION
**Pull request by Tardo**
cc @tecnativa TT27254

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Needed in v13 as well?

**Review by chienandalu — APPROVED** [review]

**Review by carlosdauden — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@Tardo please modify tests according the change.

**Comment by Tardo** [comment]
Changes done

**Pull request merged**
