### PR TITLE
[15.0][MIG] account_invoice_line_sale_line_position

### PR DESCRIPTION
**Pull request by ajaniszewska-dev**

### CODE REVIEW

**Review by grindtildeath — APPROVED** [review]
:+1:

**Review by ivantodorovich — APPROVED** [review]

**Review by TDu — APPROVED** [review]

**Comment by ajaniszewska-dev** [comment]
@pedrobaeza  can we merge?

**Comment by pedrobaeza** [comment]
Please put PR title as I have changed it next time.

/ocabot migration account_invoice_line_sale_line_position
/ocabot merge nobump

**Pull request merged**
