### PR TITLE
[16.0][FIX] account_invoice_report_grouped_by_picking: Show lines/section in manually created invoice lines

### PR DESCRIPTION
**Pull request by manuelregidor**
Based on https://github.com/OCA/account-invoice-reporting/pull/308

T-5953

### CODE REVIEW

**Comment by manuelregidor** [comment]
@Jesarregui @HaraldPanten @ValentinVinagre

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Review by HaraldPanten — APPROVED** [review]

**Pull request merged**
