### PR TITLE
[13.0][MIG] account_reporting_net_weight: Migration to 13.0

### PR DESCRIPTION
**Pull request by cubells**
Depends on 

- [x] product_net_weight: https://github.com/OCA/product-attribute/pull/1098

Standard migration.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@cubells can you please rebase and check CIs?

**Comment by pedrobaeza** [comment]
Oh, I think I can do it:

/ocabot rebase

**Comment by pedrobaeza** [comment]
Please check tests

**Comment by cubells** [comment]
@pedrobaeza done

thanks!

**Pull request merged**
