### PR TITLE
Rename invoice_condition_template and improve its UI

### PR DESCRIPTION
**Pull request by guewen**
Rename invoice_condition_template to invoice_comment_template, and base_condition_template to base_comment_template (as proposed here: https://github.com/OCA/sale-reporting/pull/18#issuecomment-64691382)

Move the condition fields in a new page

They take too much place on the 'Order Lines' page. Also I improved the
general layout of the fields.

Rename 'Condition' to 'Comment' because the texts are not 'conditions'

Same changes have been done in sale_condition_template: https://github.com/OCA/sale-reporting/pull/18

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by guewen** [comment]
@pedrobaeza I renamed the modules here to follow on on your proposition here https://github.com/OCA/sale-reporting/pull/18 so could you revise your review? thanks!

**Comment by pedrobaeza** [comment]
Thank you very much for taking my suggestion in mind. The only remaining thing I see is that the pot files are not renamed to `comment`. The rest LGTM.

**Comment by guewen** [comment]
Oh! Right! That's done now. Thanks

**Comment by pedrobaeza** [comment]
I should fast track this PR for removing ASAP the other module name. Do you agree?

**Comment by lepistone** [comment]
:+1: thanks!

**Comment by guewen** [comment]
Thanks @pedrobaeza and @lepistone

**Pull request merged**
