### PR TITLE
[15.0][FIX] account_invoice_report_grouped_by_picking: reports of credit notes without lines.

### PR DESCRIPTION
**Pull request by angelgarciadelachica**
Same fix as in PR https://github.com/OCA/account-invoice-reporting/pull/312

[I-5787]

### CODE REVIEW

**Comment by angelgarciadelachica** [comment]
@HaraldPanten @ValentinVinagre

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Review by HaraldPanten — APPROVED** [review]
LGTM

**Pull request merged**
