### PR TITLE
8.0 migrate partner-aging

### PR DESCRIPTION
**Pull request by JehoG**
Not sure about the lenght of the SQL queries (>80).
Should I cut those lines?

### CODE REVIEW

**Comment by JehoG** [comment]
Maybe check the modification in this commit too, not sure about the copyright changes:
https://github.com/savoirfairelinux/account-invoice-reporting/commit/3fa9cae988b87487324fc44bda0766f99ddb2958

**Comment by rvalyi** [comment]
Hello @JehoG 

I didn't dig into the code. But two remarks:

1) doesn't it overlap existing OCA module account_due_list https://github.com/OCA/account-payment/tree/8.0/__unported__/account_due_list ? Is it better (may be). Could you elaborate how it would compare?
2) OCA has the policy of having a discrete branding, so companies logos aren't accepted and you should make that file company agnostic partner_aging/static/description/Logo.png (same rule for everybody).

Thanks for your time.

**Comment by max3903** [comment]
Hello @rvalyi,

partner_aging provides the 30-days, 60-days, 90-days and 120-days aged amounts:
customer aging openerp

Does account_due_list provide that info and allow grouping by partners ?

**Comment by max3903** [comment]
Original author has not signed the CLA yet.

**Comment by bwrsandman** [comment]
The author has now signed

**Comment by bwrsandman** [comment]
@JehoG is covered by Savoir-faire Linux CLA

**Comment by max3903** [comment]
:+1:

**Comment by ghost** [comment]
:-1: This module does not work. Just try to create an invoice with multiple payment term lines, and see the result.

Also, the whole module is made of sql queries. This is not maintainable.

**Comment by JordiBForgeFlow** [comment]
This PR solves the same need, and it is much more simple: https://github.com/OCA/account-payment/pull/94

**Comment by JordiBForgeFlow** [comment]
O also had bad experience with this module. Did not work properly

**Comment by pedrobaeza** [comment]
As there's no answer, I close. Feel free to reopen in case there's interest.

**Pull request closed without merging**
