### PR TITLE
Mrp cancel

### PR DESCRIPTION
**Pull request by bwrsandman**
Split of #24

### CODE REVIEW

**Comment by eLBati** [comment]
It seems this PR has wrong target

**Comment by bwrsandman** [comment]
Where should it go?

**Comment by pedrobaeza** [comment]
I suppose in https://github.com/OCA/manufacture

**Comment by gurneyalex** [comment]
yep wrong target 
:-1:

@max3903 do you know if someone at savoirfairelinux still has an interest in this?

**Comment by ghost** [comment]
@gurneyalex you may close this PR

**Comment by feketemihai** [comment]
@pedrobaeza Can you please close this one.

**Pull request closed without merging**
