### PR TITLE
[IMP] [7.0] PEP8

### PR DESCRIPTION
**Pull request by eLBati**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
There's a problem with missing security rules, but PEP8 is OK, so :+1:

**Comment by bwrsandman** [comment]
I suggest fixing the security rule, the tests will be green after that.

**Comment by tafaRU** [comment]
PEP8 is OK, so one more :+1:

**Comment by tafaRU** [comment]
The security rule needs to be fixed in https://github.com/OCA/reporting-engine/tree/7.0/base_report_assembler So I think this PR can me merged as is.

**Comment by yvaucher** [comment]
:+1:

**Pull request merged**
