### PR TITLE
[15.0] Migration of account_comment_template

### PR DESCRIPTION
**Pull request by alan196**
### Proposed changes

Migration PR for module account_comment_template.

### Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Migration Update

### Checklist

- [x] I have read the CONTRIBUTING doc
- [x] I have signed the CLA
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated the necessary documentation

### Comments

This PR depends on https://github.com/OCA/reporting-engine/pull/619

### CODE REVIEW

**Review by hailangvn — APPROVED** [review]
Functional test ok. Thanks for the work.

**Comment by marylla** [comment]
@alan196 Could you please rebase your PR? Thanks a lot. :)

**Comment by alan196** [comment]
@marylla sorry I was on holiday. Rebased 👍

**Review by marylla — APPROVED** [review]
I made a functional review.
I could create and add the prefix and suffix comment to invoices and print it.
It works as expected. :+1:

**Pull request merged**
