### PR TITLE
[12.0][FIX] account_reporting_weight: weight is always zero

### PR DESCRIPTION
**Pull request by cubells**
Fix query to create view in a correct manner.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why the factors would be `NULL`? There's always both UoMs. And also don't remove the RST file.

**Comment by cubells** [comment]
SQL must be altered by some changes after the module was published and now module does not work. See:

image


With these changes, all works now again.

I restore file again, but one question:

Do you want to not delete the file by historical reasons or for what? For me content of this file make no sense now.

**Comment by pedrobaeza** [comment]
> SQL must be altered by some changes after the module was published and now module does not work. See:

Isn't that due to bad demo data? Is this happening in real DBs? `factor` and `factor2` shouldn't be `NULL` having both uom (the product and the invoice ones). That's why I'm wondering why it happens.

> Do you want to not delete the file by historical reasons or for what? For me content of this file make no sense now.

Isn't that recommendation still valid?

**Comment by cubells** [comment]
You are right @pedrobaeza , in a production database, weight is calculated.

So I close this PR.

Thanks

**Pull request closed without merging**
