### PR TITLE
13.0 mig base comment template

### PR DESCRIPTION
**Pull request by emagdalenaC2i**

### CODE REVIEW

**Comment by emagdalenaC2i** [comment]
@pedrobaeza I don't know why travis is red. I did the same than in other migration PR
Some clue?

**Comment by pedrobaeza** [comment]
The error is "Check that executables have shebangs", which means that you have marked any file as executable.

**Comment by emagdalenaC2i** [comment]
But i didn't do that

**Comment by pedrobaeza** [comment]
Ok, but it should be fixed any way

**Pull request closed without merging**
