### PR TITLE
[13.0][IMP] account_invoice_report_grouped_by_picking: No display repeated lines for refund invoices without no returned quantities

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa TT27550
ping @carlosdauden 

Before this PR:
image

After this PR:
image

### CODE REVIEW

**Comment by pedrobaeza** [comment]
But should we keep the original amount in the line in these cases? Some customers will expect so, and other will expect to have 0 quantity.

**Comment by sergio-teruel** [comment]
@pedrobaeza is for v13.0
I do not understand your approach

**Comment by pedrobaeza** [comment]
Having this situation:

- Delivered 10 units
- Refund that 10 units via accounting, not via return picking.

What do you want to show in the invoice? 10 or 0 units?

**Comment by sergio-teruel** [comment]
Se can discuss about your query, but this PR does not change these behavior.
I do not know if user expects 0 or 10 units but O am sure that user not expects a line with 20 units and another one with -10 units...

**Comment by pedrobaeza** [comment]
OK, let's try to fix that one. Can you add a regression test for the use case?

**Comment by sergio-teruel** [comment]
@pedrobaeza Tests added!!

**Comment by sergio-teruel** [comment]
I am seeing that some lines has not been covered by tests ... 
Plase wait to improve the tests for merge it...

**Review by chusamo — APPROVED** [review]
Tested in Local LGTM

**Review by carlosdauden — APPROVED** [review]

**Pull request merged**
