### PR TITLE
[16.0][MIG] account_invoice_report_due_list: Migration to 16.0

### PR DESCRIPTION
**Pull request by Tisho99**
Supersedes #282 as inactive

### CODE REVIEW

**Comment by Tisho99** [comment]
@HaraldPanten

**Review by HaraldPanten — APPROVED** [review]
Tested in runboat

**Comment by HaraldPanten** [comment]
@pedrobaeza I think we can merge this one. We kept the authorship.

THX

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
