### PR TITLE
[13.0] [MIG] account_invoice_comment_template

### PR DESCRIPTION
**Pull request by feketemihai**

### CODE REVIEW

**Comment by feketemihai** [comment]
Depends on #149

**Comment by feketemihai** [comment]
Superseeded #131 
@jimhoefnagels Can you please check this.

**Comment by feketemihai** [comment]
Depends on #149  and PR for moving base_comment_template to reporting-engine: https://github.com/OCA/reporting-engine/pull/417

**Comment by marylla** [comment]
Hi there,
I started a functional review and I got the following exception after clicking on menu Invoicing > Configuration > Account Invoice Comments. I don't know if this is caused by this module or by base_comment_template.

@feketemihai Can you check this please?

(Sorry, I accidentally added this comment before in the wrong PR.)

<pre>
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/.repo_requirements/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/.repo_requirements/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/.repo_requirements/odoo/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/.repo_requirements/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/.repo_requirements/odoo/addons/web/controllers/main.py", line 1285, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/.repo_requirements/odoo/addons/web/controllers/main.py", line 1304, in do_search_read
    return Model.web_search_read(domain, fields, offset=offset, limit=limit, order=sort)
  File "/.repo_requirements/odoo/addons/web/models/models.py", line 39, in web_search_read
    records = self.search_read(domain, fields, offset=offset, limit=limit, order=order)
  File "/.repo_requirements/odoo/odoo/models.py", line 4912, in search_read
    records = self.search(domain or [], offset=offset, limit=limit, order=order)
  File "/.repo_requirements/odoo/odoo/models.py", line 1643, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/.repo_requirements/odoo/odoo/models.py", line 4457, in _search
    query = self._where_calc(args)
  File "/.repo_requirements/odoo/odoo/models.py", line 4177, in _where_calc
    e = expression.expression(domain, self)
  File "/.repo_requirements/odoo/odoo/osv/expression.py", line 677, in __init__
    self.parse()
  File "/.repo_requirements/odoo/odoo/osv/expression.py", line 858, in parse
    raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
ValueError: Invalid field 'model' in leaf "osv.ExtendedLeaf: ('model', '=', 'account.move') on base_comment_template (ctx: ) "
</pre>

**Comment by feketemihai** [comment]
@marylla i will check them later and let you know, last time they were fine and I could test also in the runbot.

**Comment by joao-p-marques** [comment]
@feketemihai can you close this is favor of #174?

**Comment by feketemihai** [comment]
Superseeded by #174

**Pull request closed without merging**
