### PR TITLE
Account payment cc

### PR DESCRIPTION
**Pull request by bwrsandman**
Split of #24

### CODE REVIEW

**Comment by eLBati** [comment]
It seems this PR has wrong target

**Comment by bwrsandman** [comment]
Where should it go?

**Comment by pedrobaeza** [comment]
In this case, it seems a mix of account-payment and HR stuff. I would close it and let the original authors to work on it if interested.

**Comment by bwrsandman** [comment]
@max3903 what do you think?

**Comment by max3903** [comment]
:+1: to move it to account_payment

**Pull request closed without merging**
