### PR TITLE
[MIG] invoice_webkit and account_draft_invoice_print

### PR DESCRIPTION
**Pull request by charbeljc**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please rename invoice_webkit to account_invoice_webkit.

**Comment by yvaucher** [comment]
@pedrobaeza we already accepted https://github.com/OCA/account-invoice-reporting/pull/14

I don't think account_invoice_\* has more value than invoice_*

**Comment by pedrobaeza** [comment]
My reasoning is to always put area/application as first word. If we couldn't do it in the other module, we can still do it in this one.

**Comment by eLBati** [comment]
Tried on
http://3112963-26-4786b0.runbot1.odoo-community.org (**_all** DB)
open SAJ/2015/004 and clicked on 'print'.

Get

> Bad Report Reference
> This report is not loaded into the database: account.report_invoice

**Comment by feketemihai** [comment]
@pedrobaeza I think this one should be closed as well since a lot of time without activity.

**Pull request closed without merging**
