### PR TITLE
 [MIG] account_reporting_weight: Migration to 11.0

### PR DESCRIPTION
**Pull request by chienandalu**
This module adds the measure "Weight" in the invoices analysis view. This is
caught from 2 possible sources:

* If the UoM of the product is one of the category "Weight", the value is taken
  from the ordered quantity.
* If the UoM of the product is another, then the weight is taken from the
  weight field of the product multiply by the ordered quantity.

cc @Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Shouldn't we use only the weight here and `product_weight_through_uom`?

**Comment by chienandalu** [comment]
The weight measure is not available in this report. Anyway, we can make it dependant on `product_weight_through_uom` and simplify the query

**Comment by pedrobaeza** [comment]
Yes, what I'm proposing is to simplify query, but no need to depend on the other module: if you have it, better for data integrity, but no real need.

**Comment by chienandalu** [comment]
Done

**Review by pedrobaeza — APPROVED** [review]

**Review by cubells — APPROVED** [review]
:+1: 

LGTM

Code review and test

**Review by cristinamartinrod — APPROVED** [review]
Works fine 👍🏻

**Pull request merged**
