### PR TITLE
[FIX] account_reporting_weight: Deleted the group by of mesures

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT22080

### CODE REVIEW

**Comment by CarlosRoca13** [comment]
@pedrobaeza This is the fix for the branch 12.0

**Review by pedrobaeza — APPROVED** [review]

**Review by sergio-teruel — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Please fix
```
account_reporting_weight/reports/account_invoice_report.py:27:1: W391 blank line at end of file
```

**Comment by CarlosRoca13** [comment]
@pedrobaeza change done!

**Pull request merged**
