### PR TITLE
[17.0][MIG] partner_time_to_pay: Migration to 17.0

### PR DESCRIPTION
**Pull request by BernatObrador**
Module migrated to version 17.0

cc https://github.com/APSL 158293

@miquelalzanillas @lbarry-apsl @mpascuall @peluko00 @javierobcn @ppyczko please review

### CODE REVIEW

**Review by mpascuall — APPROVED** [review]
LGTM, checked in runboat

**Review by peluko00 — APPROVED** [review]
LGTM, code review and tested in runboat

**Review by ppyczko — APPROVED** [review]
LGTM, code review and tested in runboat

**Comment by BernatObrador** [comment]
@pedrobaeza Is this ready to merge?

**Comment by pedrobaeza** [comment]
/ocabot migration partner_time_to_pay

A PSC or module maintainer should confirm, as I don't use this module.

**Comment by BernatObrador** [comment]
@max3903 Is this ready to merge?

**Pull request merged**
