### PR TITLE
[16.0][mig] account_invoice_production_lot

### PR DESCRIPTION
**Pull request by aktiv-heli-kantawala**

### CODE REVIEW

**Comment by matteoopenf** [comment]
@heliaktiv  can you do a rebase?
I want test on rubboat to approve
Thank you

**Review by matteoopenf — APPROVED** [review]

**Review by matteoopenf — APPROVED** [review]
I try in local env and it works fine

**Review by lorenzoallegrucci — APPROVED** [review]

**Review by patrickt-oforce — APPROVED** [review]

**Comment by matteoopenf** [comment]
@pedrobaeza is it possibile have a rebase?
thank you

**Comment by matteoopenf** [comment]
@etobella  is it possibile have rebase? Because in locale env it works and we need the module 
thank you so much for the help

**Review by etobella — APPROVED** [review]
Let's wait for tests and then I will merge :wink:

**Comment by matteoopenf** [comment]
> Let's wait for tests and then I will merge 😉

thank you

**Pull request merged**
