### PR TITLE
[13.0] [MIG] Move base_comment_template to reporting-engine, add oca_dependencies

### PR DESCRIPTION
**Pull request by feketemihai**

### CODE REVIEW

**Comment by feketemihai** [comment]
Superseeded https://github.com/OCA/account-invoice-reporting/pull/121

**Comment by feketemihai** [comment]
@pedrobaeza 
Do you know how i can pass Travis, since the error is related to not founding openupgradelib in external dependencies

@emagdalenaC2i @jimhoefnagels @rven Can you please check this one, i will create anothe PR for stock_picking_comment_template to show you how easy it is to put the templates now.

**Comment by feketemihai** [comment]
Stock Picking Comment Template PR at https://github.com/OCA/stock-logistics-reporting/pull/109

**Comment by rousseldenis** [comment]
@pedrobaeza Do you have an advice on this as I feel it should be in another repo, no ?

**Comment by pedrobaeza** [comment]
Well, the history about this is long:

- First it was only one module with the templates and the invoice part.
- Then it was split in 2 for using the base templates in other parts (like sale, pickings, etc).
- But it remained here in this repo with the "main" dependency.

**Comment by feketemihai** [comment]
@pedrobaeza @rousseldenis In the PR description i added a comment to be moved probably to reporting-engine or server-ux

**Comment by feketemihai** [comment]
@pedrobaeza @rousseldenis We can live it here for 13.0 and move it from 14.0, for me reporting-engine would make more sense, but it's up to you.

**Review by AaronHForgeFlow — COMMENTED** [review]
Only functional tests. Works as expected I think.

Only, one thing. The active button displays badly:
image

I think reporting engine may be the proper repo, but that is not blocking for me.

**Comment by pedrobaeza** [comment]
Please check https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0 with instructions about the new way of handling active smart-buttons (through a ribbon).

**Comment by pedrobaeza** [comment]
Let's move it to OCA/reporting-engine as everyone agrees.

**Comment by feketemihai** [comment]
@pedrobaeza @AaronHForgeFlow @rousseldenis Moved the module to reporting-engine, PR https://github.com/OCA/reporting-engine/pull/417
I adjusted also the Archive button and the one2many widget in partner view.

I would leave this PR since i added the oca-dependencies.text file to reference reporting-engine repo.

**Comment by feketemihai** [comment]
@pedrobaeza Can we open this one, the PR was to add the oca-dependencies file referencing reporting-engine repo.

**Comment by pedrobaeza** [comment]
But it stills contains the commit history... You can use anyway the same branch for doing another PR, and I don't see it interesting unless you add account_invoice_comment_template module. Then, you can add the repo on oca_dependencies.txt

**Comment by feketemihai** [comment]
@pedrobaeza Done in #150 . Thanks.

**Comment by MrTango** [comment]
Hi I'm a bit lost with this many referencing PR's, where is the current one for base_comment_template for 13.0?

**Pull request closed without merging**
