### PR TITLE
fix the new page bug with latest wkhtmltopdf

### PR DESCRIPTION
**Pull request by arthru**

### CODE REVIEW

**Comment by arthru** [comment]
Note that the travis status is not related to that change

**Comment by pedrobaeza** [comment]
Can you please rebase?

**Comment by arthru** [comment]
Just rebased !

**Comment by pedrobaeza** [comment]
I didn't know about `loop.last`. Thanks for the tip!

:+1:

**Comment by eLBati** [comment]
:+1:

**Comment by bwrsandman** [comment]
:+1:

**Pull request merged**
