### PR TITLE
[12.0][FIX] partner_time_to_pay

### PR DESCRIPTION
**Pull request by bodedra**
This PR will fix/improve following:

- Fix Receivable & Payable calculation and enhance it with including child records
- Re-arrangement of fields to display under correct section

### CODE REVIEW

**Comment by bodedra** [comment]
Ping @max3903 @smangukiya

**Comment by bodedra** [comment]
@cubells @victoralmau @carlosdauden @chienandalu

I am getting some errors from your module. Would you please check it.

Module name: account_invoice_report_due_list

**Review by chienandalu — COMMENTED** [review]
It could be that the date check fell between days. I'm relaunching Travis to see

**Comment by bodedra** [comment]
> It could be that the date check fell between days. I'm relaunching Travis to see

@chienandalu Appreciate your quick fix. Now travis is :green_circle: Thank you.

**Review by smangukiya — APPROVED** [review]

**Comment by bodedra** [comment]
@jcdrubay will appreciate your valuable feedback on this PR.

**Pull request closed without merging**
