### PR TITLE
[12.0][MIG] account_invoice_report_grouped_by_picking: Migration to 12.0

### PR DESCRIPTION
**Pull request by ioans73**
Standard migration to 12.0

### CODE REVIEW

**Review by Abranes — APPROVED** [review]

**Review by Saphery — APPROVED** [review]

**Review by Jortolsa-S73 — APPROVED** [review]

**Review by jesusVMayor — CHANGES_REQUESTED** [review]
Tested on runbot. Fails when the invoice has a section

> Error:
> Odoo Server Error
> 
> Traceback (most recent call last):
>   File "/.repo_requirements/odoo/odoo/addons/base/models/qweb.py", line 346, in _compiled_fn
>     return compiled(self, append, new, options, log)
>   File "<template>", line 1, in template_account_report_invoice_document_with_payments_388
>   File "<template>", line 2, in body_call_content_387
>   File "<template>", line 94, in foreach_363
> TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/odoo/OCB-12.0/addons/web/controllers/main.py", line 1671, in report_download
>     response = self.report_routes(reportname, docids=docids, converter=converter)
>   File "/.repo_requirements/odoo/odoo/http.py", line 519, in response_wrap
>     response = f(*args, **kw)
>   File "/home/odoo/OCB-12.0/addons/web/controllers/main.py", line 1612, in report_routes
>     pdf = report.with_context(context).render_qweb_pdf(docids, data=data)[0]
>   File "/.repo_requirements/odoo/odoo/addons/base/models/ir_actions_report.py", line 711, in render_qweb_pdf
>     html = self.with_context(context).render_qweb_html(res_ids, data=data)[0]
>   File "/.repo_requirements/odoo/odoo/addons/base/models/ir_actions_report.py", line 751, in render_qweb_html
>     return self.render_template(self.report_name, data), 'html'
>   File "/.repo_requirements/odoo/odoo/addons/base/models/ir_actions_report.py", line 534, in render_template
>     return view_obj.render_template(template, values)
>   File "/.repo_requirements/odoo/odoo/addons/base/models/ir_ui_view.py", line 1299, in render_template
>     return self.browse(self.get_view_id(template)).render(values, engine)
>   File "/home/odoo/OCB-12.0/addons/web_editor/models/ir_ui_view.py", line 27, in render
>     return super(IrUiView, self).render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
>   File "/.repo_requirements/odoo/odoo/addons/base/models/ir_ui_view.py", line 1308, in render
>     return self.env[engine].render(self.id, qcontext)
>   File "/.repo_requirements/odoo/odoo/addons/base/models/ir_qweb.py", line 59, in render
>     result = super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
>   File "/.repo_requirements/odoo/odoo/addons/base/models/qweb.py", line 274, in render
>     self.compile(template, options)(self, body.append, values or {})
>   File "/.repo_requirements/odoo/odoo/addons/base/models/qweb.py", line 348, in _compiled_fn
>     raise e
>   File "/.repo_requirements/odoo/odoo/addons/base/models/qweb.py", line 346, in _compiled_fn
>     return compiled(self, append, new, options, log)
>   File "<template>", line 1, in template_685_324
>   File "<template>", line 2, in body_call_content_323
>   File "<template>", line 3, in foreach_322
>   File "/.repo_requirements/odoo/odoo/addons/base/models/qweb.py", line 353, in _compiled_fn
>     raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
> odoo.addons.base.models.qweb.QWebException: unsupported operand type(s) for +: 'NoneType' and 'int'
> Traceback (most recent call last):
>   File "/.repo_requirements/odoo/odoo/addons/base/models/qweb.py", line 346, in _compiled_fn
>     return compiled(self, append, new, options, log)
>   File "<template>", line 1, in template_account_report_invoice_document_with_payments_388
>   File "<template>", line 2, in body_call_content_387
>   File "<template>", line 94, in foreach_363
> TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
> 
> Error to render compiling AST
> TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
> Template: account.report_invoice_document_with_payments
> Path: /templates/t/t/div/table/tbody/t[2]/t[8]
> Node: <t t-if="current_section and (line_last or o.invoice_line_ids[line_index+1].display_type == 'line_section')">
>                                     <tr class="is-subtotal text-right">
>                                         <td colspan="99">
>                                             <strong class="mr16">Subtotal</strong>
>                                             <span t-esc="current_subtotal" t-options="{&quot;widget&quot;: &quot;monetary&quot;, &quot;display_currency&quot;: o.currency_id}"/>
>                                         </td>
>                                     </tr>
>                                 </t>
>

**Comment by acysos** [comment]
Hello,

I confirm the same error that comment @jesusVMayor. I'm solving the bug.

Greetings

**Comment by acysos** [comment]
Hello,

I confirm the same error that comment @jesusVMayor.

Greetings

**Comment by acysos** [comment]
Hello,

I have found the problem, is the total when use a section. They are incompatible, you can use this module with sections for the moment.

Greetings

**Comment by acysos** [comment]
PR done to fix the bug detected by @jesusVMayor 
https://github.com/Studio73/account-invoice-reporting/pull/1
@ioans73

**Comment by fuentes73** [comment]
@ioans73, please check travis and make it green

**Comment by pedrobaeza** [comment]
CIs are red. Please check.

**Comment by ioans73** [comment]
Fixed, now it's :green_apple:

**Pull request merged**
