### PR TITLE
[17.0][MIG] account_invoice_report_grouped_by_picking: Migration to 17.0

### PR DESCRIPTION
**Pull request by lethuthao2403**
ref: [BSRD-699](https://jira.camptocamp.com/browse/BSRD-699)

### CODE REVIEW

**Comment by gurneyalex** [comment]
hello @lethuthao2403 I'm merging https://github.com/OCA/stock-logistics-workflow/pull/1446 you should be able to remove the unreleased dependency.

**Comment by lethuthao2403** [comment]
> hello @lethuthao2403 I'm merging [OCA/stock-logistics-workflow#1446](https://github.com/OCA/stock-logistics-workflow/pull/1446) you should be able to remove the unreleased dependency.

@gurneyalex the PR has been updated! Thanks.

**Review by gurneyalex — APPROVED** [review]

**Pull request merged**
