### PR TITLE
[14.0][FIX] account_invoice_report_grouped_by_picking: filter sections and notes

### PR DESCRIPTION
**Pull request by miguel-S73**
cherry-pick https://github.com/OCA/account-invoice-reporting/pull/193
cherry-pick https://github.com/OCA/account-invoice-reporting/pull/206

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please check Travis

**Comment by pedrobaeza** [comment]
Any news about red CI @miguels73 ?

**Comment by miguel-S73** [comment]
@pedrobaeza , I have fixed Travis error report using this solution https://github.com/OCA/account-invoice-reporting/pull/206

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Fast-tracking as it's already merged in previous version:

/ocabot merge patch

**Pull request merged**
