### PR TITLE
[16.0] [MIG] account_comment_template

### PR DESCRIPTION
**Pull request by AMhadhbi**

### CODE REVIEW

**Comment by AMhadhbi** [comment]
blocked by (https://github.com/OCA/reporting-engine/pull/664)

**Comment by marylla** [comment]
Hi @AMhadhbi The PR for base_comment_template (https://github.com/OCA/reporting-engine/pull/664) is now merged. Can you rebase your PR?

**Comment by AMhadhbi** [comment]
@marylla PR is ready for review

**Review by marylla — CHANGES_REQUESTED** [review]
I made a functional review.
It actually works fine. I can add prefix and suffix texts and they are printed in invoice report.

But I have 2 problems you might be able to help me with:

1. Do you know how to use the editor in odoo 16? Because I unfortunately don't. :( 
In Odoo 14 I had a formatting bar above the text field, and in Odoo 15 I needed to "highlight" the word and the formatting bar appeared. How do I make some words bold or underlined or similiar stuff.

2. If I create a new comment template and click on "preview" smartbutton without saving the comment first, I get this exception:

<pre>
UncaughtPromiseError > EvaluationError
Uncaught Promise > Name 'active_id' is not defined

EvaluationError: Name 'active_id' is not defined
    at _evaluate (http://oca-account-invoice-reporting-16-0-pr242-0881075be858.runboat.odoo-community.org/web/assets/407-1240bdf/web.assets_backend.min.js:1248:232)
    at _evaluate (http://oca-account-invoice-reporting-16-0-pr242-0881075be858.runboat.odoo-community.org/web/assets/407-1240bdf/web.assets_backend.min.js:1250:109)
    at evaluate (http://oca-account-invoice-reporting-16-0-pr242-0881075be858.runboat.odoo-community.org/web/assets/407-1240bdf/web.assets_backend.min.js:1261:8)
    at evaluateExpr (http://oca-account-invoice-reporting-16-0-pr242-0881075be858.runboat.odoo-community.org/web/assets/407-1240bdf/web.assets_backend.min.js:1111:109)
    at makeContext (http://oca-account-invoice-reporting-16-0-pr242-0881075be858.runboat.odoo-community.org/web/assets/407-1240bdf/web.assets_backend.min.js:241:375)
    at Object.doActionButton (http://oca-account-invoice-reporting-16-0-pr242-0881075be858.runboat.odoo-community.org/web/assets/407-1240bdf/web.assets_backend.min.js:5740:16)
    at async execute (http://oca-account-invoice-reporting-16-0-pr242-0881075be858.runboat.odoo-community.org/web/assets/407-1240bdf/web.assets_backend.min.js:5411:288)
    </pre>
    
    Can you fix this?

**Comment by AMhadhbi** [comment]
@marylla thanks for your test and review. 
i checked the issue and it was because the field comment is HTML and required, it should be blocked in save action
I guess this is a standard issue in v16 , the required HTML field it is not shown in the widget in create action, in v14 and v15 worked as expected for odoo standard.

I tested in runbot v16 for lunch app, i created alert and the field message is HTML field and required and it is not shown as required field in the widget as in v15
as you can see her
Screenshot 2022-11-02 at 11 41 53 AM
Screenshot 2022-11-02 at 11 41 36 AM

**Comment by victoralmau** [comment]
Please, cherry-pick https://github.com/OCA/account-invoice-reporting/pull/254 to commit history

**Review by alan196 — APPROVED** [review]
Technical & Functional Review 👍 

I have read the commit https://github.com/OCA/account-invoice-reporting/pull/254, and I think it's already done in the migration of this tests

**Comment by victoralmau** [comment]
> Technical & Functional Review +1
> 
> I have read the commit #254, and I think it's already done in the migration of this tests

Checking the migration, I see that https://github.com/OCA/account-invoice-reporting/pull/254 is missing, the commit should be added in the commit history before the migration commit.

**Comment by bealdav** [comment]
Hi all, thanks for your contribution.
What is the state of PR ? Is there something todo ?
Thanks in advance

**Comment by bealdav** [comment]
I made this PR to add missing commit https://github.com/blooparksystems/account-invoice-reporting/pull/1
Cherry pick add confuse info, then a new commit with the right author. Feel free to review and merge this new PR to continue on this one cc @victoralmau @AMhadhbi

**Comment by victoralmau** [comment]
Please, cherry-pick https://github.com/OCA/account-invoice-reporting/pull/254 to commit history.

**Review by Yadier-Tecnativa — COMMENTED** [review]
LGTM, I mean the code. But in the history commits like you say, the last option to finally close the PR seems the best option.

**Comment by bealdav** [comment]
@Yadier-Tecnativa thanks for your interest here.

What is LGTM ?

- current PR
- current PR but require missing cherry pick
- current PR with additional code https://github.com/blooparksystems/account-invoice-reporting/pull/1 equivalent to cherry pick from code authors point of view without headache inherited from cherry picking in this particular case

In other words, how can we make this module finally migrated, with all required code and authors rights ?

My proposal seems to be the easier way to do it !?

What do you think ?

**Comment by Yadier-Tecnativa** [comment]
TT42208 ping @victoralmau @pedrobaeza

**Comment by Yadier-Tecnativa** [comment]
We are finally going to supersede with the refreshed history

**Comment by pedrobaeza** [comment]
Superseded by #274

**Pull request closed without merging**
