### PR TITLE
[14.0][MIG] account_invoice_report_hide_line

### PR DESCRIPTION
**Pull request by AmmarOfficewalaSerpentCS**

### CODE REVIEW

**Comment by AmmarOfficewalaSerpentCS** [comment]
@bodedra , @max3903 , @murtuzasaleh , @dreispt , 
Can you please review this PR?

**Review by bodedra — CHANGES_REQUESTED** [review]
Functional review failed.

Screenshot from 2021-04-14 09-07-24

**Comment by AmmarOfficewalaSerpentCS** [comment]
@bodedra , 
I have tested in my local and i am not able to generate an issue.
Can  you please provided step to reproduce 
Here it is a video of my testing  :-  https://drive.google.com/file/d/1xLJo1K2MD6YymaTc9xvQ5slHjAzAYyNu/view

**Comment by AmmarOfficewalaSerpentCS** [comment]
@bodedra , 
I found the issue, 
Technically template replace by account_invoice_report_grouped_by_picking this module, 
That's why changes not display.

**Comment by bodedra** [comment]
@AmmarOfficewalaSerpentCS I tried in runbot http://3476618-186-027e95.runbot2.odoo-community.org/web#id=10&action=208&model=account.move&view_type=form&cids=&menu_id=107 and have same issue. Haven't resolved yet.

**Comment by AmmarOfficewalaSerpentCS** [comment]
@bodedra 

I have fixed the code in a group by picking 
Here it is a PR link :- #189

**Comment by Freni-OSI** [comment]
needs review
CC: @patrickrwilson

**Review by patrickrwilson — APPROVED** [review]
Tested and worked great. LGTM

**Review by smangukiya — APPROVED** [review]

**Comment by smangukiya** [comment]
@dreispt : Would you mind merging this manually if possible? Thank you

**Comment by patrickrwilson** [comment]
@max3903 I think this failed to merge due to another modules test failing "account_invoice_report_due_list"

**Pull request merged**
