### PR TITLE
[14.0][FIX] account invoice report grouped by picking sold services refund

### PR DESCRIPTION
**Pull request by stefan-tecnativa**
cc @Tecnativa 

@chienandalu please review!

Now I've followed your indications.

### CODE REVIEW

**Review by chienandalu — COMMENTED** [review]
You'll have to update the repository template. Do it in a separated branch/PR and execute: `copier copy https://github.com/OCA/oca-addons-repo-template.git .` in the repository root folder

**Comment by pedrobaeza** [comment]
Please rebase

**Review by chienandalu — CHANGES_REQUESTED** [review]
The commit has not much to do with the origin one. Don't you think that maybe there are some previous commit that are missing and that you should fw as well?

**Review by chienandalu — COMMENTED** [review]
@carlosdauden please take a look

**Comment by pedrobaeza** [comment]
@carlosdauden is this still applicable?

**Pull request closed without merging**
