### PR TITLE
[14.0][MIG] account_invoice_comment_template renamed to account_comment_template 

### PR DESCRIPTION
**Pull request by petrus-v**
@OCA/accounting-maintainers (I'm not sure it's a good practice to ping PSC like this ?)

As long `account.invoice` model were removed I'm wondering if it's good time to rename module from `account_invoice_comment_template` to `account_move_comment_template` ? Any thought welcomes!

~~This MR is based on #163~~
This MR depends on [base_commet_template migration](https://github.com/OCA/reporting-engine/pull/474)

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I think it can be renamed to `account_comment_template`

**Review by alan196 — APPROVED** [review]
👍 Tested in my local

**Comment by SimoneVagile** [comment]
As planned in [https://github.com/OCA/account-invoice-reporting/pull/149#issuecomment-654258369](https://github.com/OCA/account-invoice-reporting/pull/149#issuecomment-654258369), module base_comment_template must change repository. There's an open PR here [https://github.com/OCA/reporting-engine/pull/417](https://github.com/OCA/reporting-engine/pull/417) for 13.0 version.

Could you please remove the module from this?

Note: I already open a migration PR for that here [https://github.com/OCA/reporting-engine/pull/473](https://github.com/OCA/reporting-engine/pull/473). Just a WIP :sweat_smile:

**Comment by petrus-v** [comment]
I've renamed the module and add oca dependency to [reporting-engine repo](https://github.com/OCA/reporting-engine) this PR is waiting following PR: https://github.com/OCA/reporting-engine/pull/474 migrating `base_comment_template` module

**Review by stevech091 — APPROVED** [review]
Functional test OK

**Comment by petrus-v** [comment]
As long [base_comment_template PR](https://github.com/OCA/reporting-engine/pull/474) has been merge this PR should be green, I'll rebase code to the head of the branch to trigger CI. I'm wondering If I'm allow to do it manually and how ?

**Review by AaronHForgeFlow — APPROVED** [review]
Functional review on runbot :+1:

**Review by anasuarez1 — APPROVED** [review]
Functional Review OK!

**Comment by SimoRubi** [comment]
@OCA/accounting-maintainers can this be merged?

**Pull request merged**
