### PR TITLE
[ADD][12.0] account_reporting_net_weight: new module

### PR DESCRIPTION
**Pull request by cubells**

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Let's merge it for not losing it:

/ocabot merge nobump

**Comment by pedrobaeza** [comment]
It requires to check the CI on this old branch, so I'm leaving it for now. If someone wants to switch to GH actions, I'll retry.

**Comment by pedrobaeza** [comment]
It requires to rebase and fix the things that appear.

**Comment by cubells** [comment]
@pedrobaeza rebased!

I didn't see this.

**Pull request merged**
