### PR TITLE
[15.0][MIG] account_invoice_report_grouped_by_picking: MIgratio to 15.0

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT36422

This PR depends of:

- [x] https://github.com/OCA/stock-logistics-workflow/pull/1147

This PR supersed https://github.com/OCA/account-invoice-reporting/pull/235

ping @carlosdauden @sergio-teruel

### CODE REVIEW

**Comment by CarlosRoca13** [comment]
Added pending commits and solved problems at tests

**Comment by sergio-teruel** [comment]
@CarlosRoca13 dependant module has been merged, rebase please

**Comment by CarlosRoca13** [comment]
Done @sergio-teruel

**Review by sergio-teruel — APPROVED** [review]
Functional review and code OK

**Review by ferran-S73 — APPROVED** [review]

**Comment by carlosdauden** [comment]
What about sale order with section or comment line?

**Comment by pedrobaeza** [comment]
The problem is the same on 13, 14 and 15, so that should be handled apart and then fw-port the patch.

**Pull request merged**
