### PR TITLE
13.0 mig base comment template

### PR DESCRIPTION
**Pull request by emagdalenaC2i**

### CODE REVIEW

**Comment by emagdalenaC2i** [comment]
@pedrobaeza I have tried several times in different ways but travis are still red because of the pre-commit and I have no idea why

**Comment by pedrobaeza** [comment]
Just reset executable flag in files. Maybe you are doing this in Windows?

**Comment by emagdalenaC2i** [comment]
Yes, we use Windows (the stupid SolidWorks don't work in Linux)
I have tried to reset the flags chmod -x base_comment_template/readme/CONTRIBUTORS.rst etc, delete and create new files and other ways

**Comment by pedrobaeza** [comment]
You need to access through Linux and fix that, and better to use a Linux VM for all this stuff.

**Comment by emagdalenaC2i** [comment]
Ok, finally
@bjeficent @aheficent could you review this PR?

**Review by AaronHForgeFlow — COMMENTED** [review]
It looks good. It would be awesome if we can also include the changes proposed here: https://github.com/OCA/account-invoice-reporting/pull/107/

**Comment by emagdalenaC2i** [comment]
@aheficent I just found out about that PR 5 minutes ago
I will try to merge it

**Comment by emagdalenaC2i** [comment]
Once #107 is merged I will update this PR

**Pull request closed without merging**
