### PR TITLE
[17.0][MIG] account_invoice_line_report: Migration to 17.0 

### PR DESCRIPTION
**Pull request by mostafabarmshory**

### CODE REVIEW

**Review by Sanazzzmi — APPROVED** [review]

**Review by fardinmardani — APPROVED** [review]
Thank you for following this, there was no problem running it, I tested it.
It's ok.

**Comment by pedrobaeza** [comment]
Please squash administrative commits into the generating one, and also duplicated translation commits from the same translator and language, like the image (but there are more):

imagen

https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-bots-or-weblate

**Comment by mostafabarmshory** [comment]
@pedrobaeza

I try to squashed them up. But I`m not sure about that. I try to fix items that are clear 

Would you check it again.

**Review by pedrobaeza — APPROVED** [review]
/ocabot migration account_invoice_line_report
/ocabot merge nobump

**Pull request merged**
