### PR TITLE
[15.0][MIG] account_invoice_line_report: Migration to 15.0

### PR DESCRIPTION
**Pull request by victoralmau**
Migration to 15.0

Please @carlosdauden and @sergio-teruel can you review it?

@Tecnativa TT39025

### CODE REVIEW

**Review by chienandalu — COMMENTED** [review]
Does it make sense to have two separated entries for the same report model or am I missing something?

**Comment by victoralmau** [comment]
> Does it make sense to have two separated entries for the same report model or am I missing something?

I don't know the original reason, maybe @carlosdauden can clarify it.

**Comment by carlosdauden** [comment]
This module adds option to show account.invoice.report in tree view with the posibility to create customized exportation

**Review by carlosdauden — APPROVED** [review]
Code LGTM

**Comment by carlosdauden** [comment]
Perhaps the new tree view could be added to the existing action window and remove the extra menu option.
But since these views can be heavy, it was decided to create a different menu entry.

**Comment by victoralmau** [comment]
Ping @chienandalu , can you do a review?

**Review by chienandalu — APPROVED** [review]

**Pull request merged**
