### PR TITLE
[17.0][MIG] account_invoice_line_report

### PR DESCRIPTION
**Pull request by mostafabarmshory**

### CODE REVIEW

**Review by fardinmardani — APPROVED** [review]
I ran the code and there was no problem and everything was fine.

**Review by Sanazzzmi — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Thanks for the migration. I see that you have made all the changes in the commit with message `[IMP] account_invoice_line_report: pre-commit auto fixes`, while it should be split across 2, one with the automatic changes, and the other with manual ones. Please check https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0#technical-method-to-migrate-a-module-from-160-to-170-branch for knowing the method.

Can you please change it?

**Comment by mostafabarmshory** [comment]
So, I close this one and create a new PR.

**Comment by mostafabarmshory** [comment]
Dear all @pedrobaeza  @fardinmardani @Sanazzzmi 
Here is a new PR. 
https://github.com/OCA/account-invoice-reporting/pull/305

Would you check and give me feedback pleas? It is not a very hard migration. Few changes requred.

**Pull request closed without merging**
