### PR TITLE
[15.0][IMP] account_invoice_report_grouped_by_picking: Add possibility to set custom order at lines

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT46676

ping @sergio-teruel @carlosdauden

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]
LGTM

**Review by sergio-teruel — APPROVED** [review]

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
This is not a good approach for adding hooks to be modified on custom modules, as it makes very difficult to follow the behavior on time.

Instead of passing an extra argument, move `self.invoice_line_ids.sorted(lambda ln: (-ln.sequence, ln.date, ln.move_name, -ln.id), reverse=True)` to a method that returns this sorted lines like `_get_grouped_by_picking_sorted_lines`), and you inherit such method in custom.

**Review by chienandalu — APPROVED** [review]

**Comment by CarlosRoca13** [comment]
Changed @pedrobaeza

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge patch

**Comment by carlosdauden** [comment]
Changes have not yet been merged

**Pull request merged**
